//! The `Share` type produced by Shamir secret sharing.

use crate::error::SecretSharingError;
use crate::field::FieldElement;
use core::fmt;

/// Version byte for shares produced by this crate.
pub const SHARE_VERSION: u8 = 1;

/// A single Shamir share.
///
/// A share is the evaluation of the secret-sharing polynomial at the
/// non-zero point `index`. The `value` is redacted in [`Debug`] output to
/// avoid leaking secret material through logs.
#[derive(Clone, PartialEq, Eq)]
pub struct Share {
    /// Format version of this share.
    pub version: u8,
    /// Minimum number of shares required for reconstruction.
    pub threshold: u32,
    /// Total number of shares generated by the split operation.
    pub share_count: u32,
    /// Public x-coordinate of this share (non-zero).
    pub index: u32,
    /// The y-value of the polynomial at `x = index`.
    pub value: FieldElement,
}

impl Share {
    /// Creates a new share, validating that `index` is non-zero.
    ///
    /// # Errors
    ///
    /// Returns [`SecretSharingError::InvalidShareIndex`] if `index` is zero.
    pub fn new(
        threshold: u32,
        share_count: u32,
        index: u32,
        value: FieldElement,
    ) -> Result<Self, SecretSharingError> {
        if index == 0 {
            return Err(SecretSharingError::InvalidShareIndex);
        }
        Ok(Self {
            version: SHARE_VERSION,
            threshold,
            share_count,
            index,
            value,
        })
    }
}

impl fmt::Debug for Share {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Share")
            .field("version", &self.version)
            .field("threshold", &self.threshold)
            .field("share_count", &self.share_count)
            .field("index", &self.index)
            .field("value", &"[REDACTED]")
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::field::element_from_be_bytes;

    fn sample_value() -> FieldElement {
        element_from_be_bytes(&[7]).expect("valid")
    }

    #[test]
    fn rejects_zero_index() {
        assert_eq!(
            Share::new(2, 3, 0, sample_value()),
            Err(SecretSharingError::InvalidShareIndex)
        );
    }

    #[test]
    fn debug_redacts_value() {
        let share = Share::new(2, 3, 1, sample_value()).expect("valid");
        let rendered = format!("{share:?}");
        assert!(rendered.contains("[REDACTED]"));
        assert!(!rendered.contains("value: 0x"));
    }

    #[test]
    fn accessors_and_equality() {
        let a = Share::new(2, 3, 1, sample_value()).expect("valid");
        let b = a.clone();
        assert_eq!(a, b);
        assert_eq!(a.version, SHARE_VERSION);
        assert_eq!(a.threshold, 2);
        assert_eq!(a.share_count, 3);
        assert_eq!(a.index, 1);
    }
}
