[package]
name = "payment-infra"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"
members = ["crates/*"]

[dev-dependencies]
ark-ed25519 = "0.4"
ark-ff = "0.4"
circuit = { path = "crates/circuit" }
crypto-core = { path = "crates/crypto-core" }
criterion = "0.5"
mpc = { path = "crates/mpc" }
mpcith = { path = "crates/mpcith" }
proptest = "1.4"
rand_core = "0.6"
rand_chacha = "0.3"

[[test]]
name = "smoke"
path = "tests/integration/smoke.rs"

[[bench]]
name = "dummy_bench"
path = "benches/dummy_bench.rs"
harness = false
