//! Known-answer tests for the SHAKE256 backend.
//!
//! The expected vectors are generated by an INDEPENDENT implementation
//! (CPython's `hashlib.shake_256`), not by the Rust code under test.
//!
//! Two layers are verified:
//! 1. A *raw* SHAKE256 against the canonical FIPS 202 published vectors
//!    (`SHAKE256("", 32)` and `SHAKE256("", 64)`), using the `sha3` crate
//!    directly so the test does not depend on our backend framing.
//! 2. The *framed* backend functions (`hash`, `expand`) against
//!    independently computed `SHAKE256(frame, n)` values, where `frame`
//!    is exactly the canonical encoding our backend uses.

use crypto_core::backend::{Shake256Backend, DOMAIN_FS};
use crypto_core::CryptoBackend;
use digest::ExtendableOutput;
use digest::XofReader;
use sha3::Shake256;

/// Raw SHAKE256 XOF to `out_len` bytes (no domain framing).
fn raw_shake256(input: &[u8], out_len: usize) -> Vec<u8> {
    let mut h = Shake256::default();
    digest::Update::update(&mut h, input);
    let mut r = h.finalize_xof();
    let mut buf = vec![0u8; out_len];
    r.read(&mut buf);
    buf
}

#[test]
fn raw_shake256_empty_matches_fips202() {
    // Canonical FIPS 202 test vectors (SHAKE256 of the empty string).
    let empty32 = "46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762f";
    let empty64 = "46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762f\
                   d75dc4ddd8c0f200cb05019d67b592f6fc821c49479ab48640292eacb3b7c4be";
    assert_eq!(raw_shake256(b"", 32), hex::decode(empty32));
    assert_eq!(raw_shake256(b"", 64), hex::decode(empty64));
}

#[test]
fn raw_shake256_abc_matches_fips202() {
    // Known SHAKE256("abc", 32) value.
    let abc32 = "483366601360a8771c6863080cc4114d8db44530f8f1e1ee4f94ea37e78b5739";
    assert_eq!(raw_shake256(b"abc", 32), hex::decode(abc32));
    let abc64 = "483366601360a8771c6863080cc4114d8db44530f8f1e1ee4f94ea37e78b5739\
                 d5a15bef186a5386c75744c0527e1faa9f8726e462a12a4feb06bd8801e751e4";
    assert_eq!(raw_shake256(b"abc", 64), hex::decode(abc64));
}

#[test]
fn backend_hash_matches_independent_framed_vector() {
    // SHAKE256(DOMAIN_HASH || len(data) || data, 32) computed by Python.
    let empty32 = "90293bafa7c2e0dc54c182f3874282eaef17673a3847e96706220b78a43d0574";
    let abc32 = "73f78c39ff2998aa4c07e516ae6f878e33ebdbcf6a14d0f793dd717a843b5372";
    assert_eq!(
        Shake256Backend::hash(b"").as_bytes(),
        &hex::decode(empty32)[..]
    );
    assert_eq!(
        Shake256Backend::hash(b"abc").as_bytes(),
        &hex::decode(abc32)[..]
    );
    // Assert the backend uses DOMAIN_HASH framing (not plain SHAKE256).
    assert_ne!(
        Shake256Backend::hash(b"").as_bytes(),
        &raw_shake256(b"", 32)[..]
    );
}

#[test]
fn backend_expand_matches_independent_vector() {
    // SHAKE256(DOMAIN_FS || len(data) || data, 64) computed by Python.
    let abc64 = "0d771e703f22805f2f279616295f1b1aef5c8dadd1bb3ac98619583487b60475\
                 bd9d751cd5e38d9dae27a59932cb7d196d6e17e918cc536523552eb65f7cde11";
    let out = Shake256Backend::expand(DOMAIN_FS, b"abc", 64);
    assert_eq!(out.len(), 64);
    assert_eq!(out, hex::decode(abc64));
}

mod hex {
    pub fn decode(s: &str) -> Vec<u8> {
        let s = s.replace(['\n', ' '], "");
        assert!(s.len().is_multiple_of(2), "odd hex length");
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex"))
            .collect()
    }
}
