//! Cross-implementation test vectors generated by `vectors/generate_vectors.py`.

use crypto_core::SecretBytes;
use rand_chacha::rand_core::SeedableRng;
use secret_sharing::Share;
use serde::Deserialize;

#[derive(Deserialize)]
struct VectorDocument {
    field_modulus_hex: String,
    #[allow(dead_code)]
    field_element_size_bytes: usize,
    version: u8,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
#[serde(rename_all = "snake_case")]
struct Case {
    name: String,
    secret_hex: String,
    canonical_secret_hex: String,
    threshold: u32,
    share_count: u32,
    shares: Vec<ShareVector>,
    encoded_shares_hex: Vec<String>,
    reconstruct_subsets: Vec<Vec<u32>>,
    insufficient_subset_indices: Vec<u32>,
}

#[derive(Deserialize)]
struct ShareVector {
    index: u32,
    value_hex: String,
}

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("valid hex"))
        .collect()
}

fn load_vectors() -> VectorDocument {
    let raw = include_str!("vectors/shamir_vectors.json");
    serde_json::from_str(raw).expect("valid vector JSON")
}

#[test]
fn vectors_match_python_implementation() {
    let doc = load_vectors();
    assert_eq!(
        doc.field_modulus_hex, "1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3ed",
        "field modulus must match the documented prime"
    );
    assert_eq!(doc.version, 1);

    for case in &doc.cases {
        // Decode and check the canonical encoding against Python.
        let decoded: Vec<Share> = case
            .encoded_shares_hex
            .iter()
            .enumerate()
            .map(|(i, hex)| {
                let bytes = unhex(hex);
                assert_eq!(bytes[1..5], case.threshold.to_be_bytes());
                assert_eq!(bytes[5..9], case.share_count.to_be_bytes());
                assert_eq!(bytes[9..13], case.shares[i].index.to_be_bytes());
                Share::decode(&bytes)
                    .unwrap_or_else(|e| panic!("case {}: decode failed: {e}", case.name))
            })
            .collect();

        for (share, expected) in decoded.iter().zip(&case.shares) {
            assert_eq!(share.version, doc.version);
            assert_eq!(share.index, expected.index);
            assert_eq!(
                &secret_sharing::field::element_to_be_bytes(&share.value)[..],
                &unhex(&expected.value_hex)[..]
            );
        }

        // Every listed subset of size t must reconstruct the secret.
        let secret = unhex(&case.canonical_secret_hex);
        for subset in &case.reconstruct_subsets {
            assert_eq!(subset.len(), case.threshold as usize);
            let shares: Vec<Share> = subset
                .iter()
                .map(|&idx| decoded[(idx - 1) as usize].clone())
                .collect();
            let recovered = secret_sharing::reconstruct(&shares)
                .unwrap_or_else(|e| panic!("case {}: subset {subset:?}: {e}", case.name));
            assert_eq!(
                recovered.as_bytes(),
                &secret[..],
                "case {}: subset {subset:?} mismatch",
                case.name
            );
        }

        // A too-small subset must fail.
        let small: Vec<Share> = case
            .insufficient_subset_indices
            .iter()
            .map(|&idx| decoded[(idx - 1) as usize].clone())
            .collect();
        assert!(
            secret_sharing::reconstruct(&small).is_err(),
            "case {}",
            case.name
        );

        // Splitting the padded secret is not deterministic across RNGs, but
        // reconstructing all shares from a fresh split must still match.
        let mut rng = rand_chacha::ChaCha20Rng::seed_from_u64(7);
        let original = SecretBytes::new(unhex(&case.secret_hex));
        let fresh = secret_sharing::split(
            &original,
            case.threshold as usize,
            case.share_count as usize,
            &mut rng,
        )
        .expect("valid split");
        let recovered = secret_sharing::reconstruct(&fresh).expect("valid reconstruct");
        assert_eq!(recovered.as_bytes(), &unhex(&case.canonical_secret_hex)[..]);
    }
}
